[package]
name = "bevy_logic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13.2", features = [
    # NOTE: REMOVE BEFORE RELEASE.
    # Otherwise you will need to include libbevy_dylib alongside your game if you want it to run. 
    # If you remove the "dynamic" feature, your game executable can run standalone.
    "dynamic_linking",
    # Create an empty "assets" folder if this prevents the game from running.
    "file_watcher",
] }
bevy-inspector-egui = "0.23.4"
bevy-trait-query = "0.5.1"
bevy_mod_picking = "0.18.2"
derive-new = "0.6.0"
derive_more = "0.99.17"
leafwing-input-manager = "0.13.3"

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
